const ML={0:1,1:0,2:5,3:8,4:7,5:2,6:9,7:4,8:3,9:6},MB={0:8,1:7,2:6,3:9,4:5,5:4,6:2,7:1,8:0,9:3},TY={0:7,1:4,2:9,3:6,4:1,5:8,6:3,7:0,8:5,9:2};
let allAiResults=[],allNonAiResults=[],marketData=[];
function setLoading(message,isError=false){const el=document.getElementById('loading-markets');if(!el)return;el.textContent=message;el.style.color=isError?'#ef4444':'var(--muted)'}
async function api(path){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(path,{headers:{Accept:'application/json'},cache:'no-store',signal:controller.signal});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.error||`Request gagal (${r.status})`);return body}catch(err){if(err.name==='AbortError')throw new Error('Server tidak merespons. Periksa deployment backend.');throw err}finally{clearTimeout(timer)}}
function updateCount(){const n=marketData.filter(m=>m.selected).length;document.getElementById('market-count').textContent=`${n} dipilih`}
function renderMarkets(){const list=document.getElementById('market-list'),q=(document.getElementById('market-search').value||'').trim().toUpperCase();list.innerHTML='';const filtered=marketData.filter(m=>String(m.name||m.id).toUpperCase().includes(q));if(!filtered.length){list.innerHTML='<div class="empty">Pasaran tidak ditemukan.</div>';return}filtered.forEach(m=>{const name=String(m.name||m.id).toUpperCase(),result=m.last_result==null?'':String(m.last_result).padStart(4,'0'),label=document.createElement('label');label.className='market-chip';const input=document.createElement('input');input.type='checkbox';input.value=m.id;input.checked=Boolean(m.selected);input.addEventListener('change',()=>{m.selected=input.checked;label.classList.toggle('active',input.checked);updateCount()});const title=document.createElement('span');title.className='market-name';title.textContent=name;const latest=document.createElement('span');latest.className='market-last';latest.textContent=result||'—';label.append(input,title,latest);if(m.selected)label.classList.add('active');list.appendChild(label)})}
async function loadMarkets(){setLoading('Memuat data pasaran...');try{const data=await api('/api/markets');if(!Array.isArray(data)||!data.length){setLoading('Data pasaran tidak tersedia.',true);return}marketData=data.map(m=>({...m,selected:false}));document.getElementById('loading-markets').style.display='none';document.getElementById('market-list').style.display='grid';renderMarkets();updateCount()}catch(err){console.error('loadMarkets:',err);setLoading(`Gagal memuat pasaran: ${err.message}`,true)}}
function toggleAll(value){marketData.forEach(m=>m.selected=value);renderMarkets();updateCount()}
function openTool(){document.getElementById('splitter-modal').classList.add('open');document.getElementById('splitter-input').focus()}
function closeTool(){document.getElementById('splitter-modal').classList.remove('open')}
function split3D(){const raw=document.getElementById('splitter-input').value.trim();const items=raw.split(/[\s*#|,;]+/).map(x=>x.trim()).filter(Boolean);const valid=items.filter(x=>/^\d{3}$/.test(x));const err=document.getElementById('splitter-error');if(!valid.length){err.textContent='Masukkan angka 3D terlebih dahulu.';err.style.display='block';document.getElementById('splitter-output').style.display='none';return}if(valid.length!==items.length){err.textContent=`${items.length-valid.length} item dilewati karena bukan format 3D.`;err.style.display='block'}else err.style.display='none';const cut=Math.ceil(valid.length/2),a=valid.slice(0,cut).join('*'),b=valid.slice(cut).join('*');document.getElementById('splitter-a').value=a;document.getElementById('splitter-b').value=b;document.getElementById('splitter-output').style.display='block'}
function copySplitter(id,msg){const value=document.getElementById(id).value;if(value)copyText(value,msg)}
function sumReduce(n){while(n>=10)n=String(n).split('').reduce((a,c)=>a+Number(c),0);return n}
function generateData(k){const a=[];for(let i=0;i<4;i++)a.push((k+i)%10);const ai=a.join(''),s=[];for(let d=0;d<10;d++)if(!a.includes(d))s.push(d);return{ai,nonAi:s.join(''),full:`${ai} ${s.join('')}`}}
function parseHistoryResults(raw,last){let l=[];if(raw){try{const p=typeof raw==='string'?JSON.parse(raw):raw;if(Array.isArray(p))l=p.map(String)}catch{l=String(raw).match(/\b\d{4}\b/g)||[]}}if(!l.length&&last)l=[String(last)];return l}
async function prosesPasaran(){const boxes=marketData.filter(m=>m.selected),em=document.getElementById('error-msg'),out=document.getElementById('output-container');if(!boxes.length){em.textContent='Silakan pilih minimal satu pasaran.';em.style.display='block';return}em.style.display='none';out.innerHTML='<div class="loading">Sedang menghitung...</div>';try{const data=await Promise.all(boxes.map(m=>api(`/api/markets/${encodeURIComponent(m.id)}`)));allAiResults=[];allNonAiResults=[];let html='';for(let i=0;i<boxes.length;i++){const m=data[i],name=String(m.name||boxes[i].name||m.id).toUpperCase(),r=parseHistoryResults(m.history_data,m.last_result);if(r.length<3){html+=`<div class="market-result-card"><div class="market-title">${name}</div><div style="color:#f87171;font-size:.78rem">Riwayat keluaran belum cukup (min 3 result).</div></div>`;continue}const [A1,K1,C1,E1]=r[0].padStart(4,'0').split('').map(Number),[A2,K2,C2,E2]=r[1].padStart(4,'0').split('').map(Number),[A3,K3,C3,E3]=r[2].padStart(4,'0').split('').map(Number);const r1=generateData(ML[sumReduce(K1+C1+E1)]),r2=generateData(TY[sumReduce(ML[sumReduce(A1+K1+C1+E1)]+MB[sumReduce(K1+C1+E1)]+((C2+5)%10))]),r3=generateData((sumReduce(ML[A3]+MB[C3]+K3)+8)%10),r4=generateData(((((sumReduce(C1+E1)-((C1+9)%10))%10+10)%10)+5)%10);allAiResults.push(`[ ${name} ]\n${r1.ai}\n${r2.ai}\n${r3.ai}\n${r4.ai}`);allNonAiResults.push(`[ ${name} ]\n${r1.nonAi}\n${r2.nonAi}\n${r3.nonAi}\n${r4.nonAi}`);html+=`<div class="market-result-card"><div class="market-title">${name}</div><pre>${r1.full}\n${r2.full}\n${r3.full}\n${r4.full}</pre></div>`}if(allAiResults.length)html+=`<div class="button-group"><button class="btn-copy" id="copy-ai">Salin Angka Utama</button><button class="btn-copy" id="copy-non-ai">Salin Angka Sisa</button></div>`;out.innerHTML=html;document.getElementById('copy-ai')?.addEventListener('click',copyAllAI);document.getElementById('copy-non-ai')?.addEventListener('click',copyAllNonAI)}catch(err){console.error('prosesPasaran:',err);out.innerHTML=`<div style="text-align:center;color:#f87171;padding:15px;font-size:.78rem">Gagal mengambil data: ${err.message}</div>`}}
function copyText(t,msg){if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(t).then(()=>showToast(msg)).catch(()=>fallbackCopy(t,msg));else fallbackCopy(t,msg)}
function fallbackCopy(t,msg){const ta=document.createElement('textarea');ta.value=t;ta.style.position='fixed';ta.style.left='-9999px';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');showToast(msg)}catch{window.prompt('Salin manual:',t)}finally{ta.remove()}}
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2000)}
function copyAllAI(){copyText(allAiResults.join('\n\n'),'Angka Utama Disalin!')}
function copyAllNonAI(){copyText(allNonAiResults.join('\n\n'),'Angka Sisa Disalin!')}
document.getElementById('process-button')?.addEventListener('click',prosesPasaran);document.getElementById('select-all')?.addEventListener('click',()=>toggleAll(true));document.getElementById('clear-all')?.addEventListener('click',()=>toggleAll(false));document.getElementById('market-search')?.addEventListener('input',renderMarkets);document.getElementById('open-tool')?.addEventListener('click',openTool);document.getElementById('close-tool')?.addEventListener('click',closeTool);document.getElementById('splitter-run')?.addEventListener('click',split3D);document.getElementById('copy-splitter-a')?.addEventListener('click',()=>copySplitter('splitter-a','Bagian 1 disalin!'));document.getElementById('copy-splitter-b')?.addEventListener('click',()=>copySplitter('splitter-b','Bagian 2 disalin!'));document.getElementById('splitter-modal')?.addEventListener('click',e=>{if(e.target.id==='splitter-modal')closeTool()});loadMarkets();