const ML={0:1,1:0,2:5,3:8,4:7,5:2,6:9,7:4,8:3,9:6},MB={0:8,1:7,2:6,3:9,4:5,5:4,6:2,7:1,8:0,9:3},TY={0:7,1:4,2:9,3:6,4:1,5:8,6:3,7:0,8:5,9:2};
let allAiResults=[],allNonAiResults=[];
function setLoading(message,isError=false){const el=document.getElementById('loading-markets');el.textContent=message;el.style.color=isError?'#ef4444':'var(--text-muted)'}
async function api(path){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(path,{headers:{Accept:'application/json'},cache:'no-store',signal:controller.signal});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.error||`Request gagal (${r.status})`);return body}catch(err){if(err.name==='AbortError')throw new Error('Server tidak merespons. Periksa deployment backend.');throw err}finally{clearTimeout(timer)}}
async function loadMarkets(){setLoading('Memuat data pasaran...');try{const data=await api('/api/markets');if(!Array.isArray(data)||!data.length){setLoading('Data pasaran tidak tersedia.',true);return}const loading=document.getElementById('loading-markets'),list=document.getElementById('market-list');loading.style.display='none';list.style.display='grid';list.innerHTML='';data.forEach(m=>{const name=String(m.name||m.id).toUpperCase(),label=document.createElement('label');label.className='market-chip';const input=document.createElement('input');input.type='checkbox';input.value=m.id;input.dataset.name=name;input.addEventListener('change',()=>toggleChip(input));label.append(input,document.createTextNode(name));list.appendChild(label)})}catch(err){console.error('loadMarkets:',err);setLoading(`Gagal memuat pasaran: ${err.message}`,true)}}
function toggleChip(cb){cb.parentElement.classList.toggle('active',cb.checked)}
function sumReduce(n){while(n>=10)n=String(n).split('').reduce((a,c)=>a+Number(c),0);return n}
function generateData(k){const a=[];for(let i=0;i<4;i++)a.push((k+i)%10);const ai=a.join(''),s=[];for(let d=0;d<10;d++)if(!a.includes(d))s.push(d);return{ai,nonAi:s.join(''),full:`${ai} ${s.join('')}`}}
function parseHistoryResults(raw,last){let l=[];if(raw){try{const p=typeof raw==='string'?JSON.parse(raw):raw;if(Array.isArray(p))l=p.map(String)}catch{l=String(raw).match(/\b\d{4}\b/g)||[]}}if(!l.length&&last)l=[String(last)];return l}
async function prosesPasaran(){const boxes=Array.from(document.querySelectorAll('#market-list input:checked')),em=document.getElementById('error-msg'),out=document.getElementById('output-container');if(!boxes.length){em.textContent='Silakan pilih minimal satu pasaran.';em.style.display='block';return}em.style.display='none';out.innerHTML='<div style="text-align:center;padding:20px;font-size:.85rem;color:var(--text-muted)">Sedang menghitung...</div>';try{const data=await Promise.all(boxes.map(cb=>api(`/api/markets/${encodeURIComponent(cb.value)}`)));allAiResults=[];allNonAiResults=[];let html='';for(let i=0;i<boxes.length;i++){const cb=boxes[i],m=data[i],name=String(m.name||cb.dataset.name||m.id).toUpperCase(),r=parseHistoryResults(m.history_data,m.last_result);if(r.length<3){html+=`<div class="market-result-card"><div class="market-title">${name}</div><div style="color:#ef4444;font-size:.8rem">Riwayat keluaran belum cukup (min 3 result).</div></div>`;continue}const [A1,K1,C1,E1]=r[0].padStart(4,'0').split('').map(Number),[A2,K2,C2,E2]=r[1].padStart(4,'0').split('').map(Number),[A3,K3,C3,E3]=r[2].padStart(4,'0').split('').map(Number);const r1=generateData(ML[sumReduce(K1+C1+E1)]),r2=generateData(TY[sumReduce(ML[sumReduce(A1+K1+C1+E1)]+MB[sumReduce(K1+C1+E1)]+((C2+5)%10))]),r3=generateData((sumReduce(ML[A3]+MB[C3]+K3)+8)%10),r4=generateData(((((sumReduce(C1+E1)-((C1+9)%10))%10+10)%10)+5)%10);allAiResults.push(`[ ${name} ]\n${r1.ai}\n${r2.ai}\n${r3.ai}\n${r4.ai}`);allNonAiResults.push(`[ ${name} ]\n${r1.nonAi}\n${r2.nonAi}\n${r3.nonAi}\n${r4.nonAi}`);html+=`<div class="market-result-card"><div class="market-title">${name}</div><pre>${r1.full}\n${r2.full}\n${r3.full}\n${r4.full}</pre></div>`}if(allAiResults.length)html+=`<div class="button-group"><button class="btn-copy" id="copy-ai">Salin Angka Utama</button><button class="btn-copy" id="copy-non-ai">Salin Angka Sisa</button></div>`;out.innerHTML=html;document.getElementById('copy-ai')?.addEventListener('click',copyAllAI);document.getElementById('copy-non-ai')?.addEventListener('click',copyAllNonAI)}catch(err){console.error('prosesPasaran:',err);out.innerHTML=`<div style="text-align:center;color:#ef4444;padding:15px;font-size:.85rem">Gagal mengambil data: ${err.message}</div>`}}
function copyText(t,msg){if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(t).then(()=>showToast(msg)).catch(()=>fallbackCopy(t,msg));else fallbackCopy(t,msg)}
function fallbackCopy(t,msg){const ta=document.createElement('textarea');ta.value=t;ta.style.position='fixed';ta.style.left='-9999px';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');showToast(msg)}catch{window.prompt('Salin manual:',t)}finally{ta.remove()}}
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2000)}
function copyAllAI(){copyText(allAiResults.join('\n\n'),'Angka Utama Disalin!')}
function copyAllNonAI(){copyText(allNonAiResults.join('\n\n'),'Angka Sisa Disalin!')}
document.getElementById('process-button')?.addEventListener('click',prosesPasaran);
loadMarkets();