const ML={0:1,1:0,2:5,3:8,4:7,5:2,6:9,7:4,8:3,9:6},MB={0:8,1:7,2:6,3:9,4:5,5:4,6:2,7:1,8:0,9:3},TY={0:7,1:4,2:9,3:6,4:1,5:8,6:3,7:0,8:5,9:2};
let allAiResults=[],allNonAiResults=[],marketData=[];
function setLoading(message,isError=false){const el=document.getElementById('loading-markets');if(!el)return;el.textContent=message;el.style.color=isError?'#ef4444':'var(--muted)'}
async function api(path){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(path,{headers:{Accept:'application/json'},cache:'no-store',signal:controller.signal});let body={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.error||`Request gagal (${r.status})`);return body}catch(err){if(err.name==='AbortError')throw new Error('Server tidak merespons. Periksa deployment backend.');throw err}finally{clearTimeout(timer)}}
function updateCount(){const n=marketData.filter(m=>m.selected).length;document.getElementById('market-count').textContent=`${n} dipilih`}
function renderMarkets(){const list=document.getElementById('market-list'),q=(document.getElementById('market-search').value||'').trim().toUpperCase();list.innerHTML='';const filtered=marketData.filter(m=>String(m.name||m.id).toUpperCase().includes(q));if(!filtered.length){list.innerHTML='<div class="empty">Pasaran tidak ditemukan.</div>';return}filtered.forEach(m=>{const name=String(m.name||m.id).toUpperCase(),result=m.last_result==null?'':String(m.last_result).padStart(4,'0'),label=document.createElement('label');label.className='market-chip';const input=document.createElement('input');input.type='checkbox';input.value=m.id;input.checked=Boolean(m.selected);input.addEventListener('change',()=>{m.selected=input.checked;label.classList.toggle('active',input.checked);updateCount()});const title=document.createElement('span');title.className='market-name';title.textContent=name;const latest=document.createElement('span');latest.className='market-last';latest.textContent=result||'—';label.append(input,title,latest);if(m.selected)label.classList.add('active');list.appendChild(label)})}
async function loadMarkets(){setLoading('Memuat data pasaran...');try{const data=await api('/api/markets');if(!Array.isArray(data)||!data.length){setLoading('Data pasaran tidak tersedia.',true);return}marketData=data.map(m=>({...m,selected:false}));document.getElementById('loading-markets').style.display='none';document.getElementById('market-list').style.display='grid';renderMarkets();updateCount()}catch(err){console.error('loadMarkets:',err);setLoading(`Gagal memuat pasaran: ${err.message}`,true)}}
function toggleAll(value){marketData.forEach(m=>m.selected=value);renderMarkets();updateCount()}
function openTool(){document.getElementById('splitter-modal').classList.add('open');document.getElementById('splitter-input').focus()}
function closeTool(){document.getElementById('splitter-modal').classList.remove('open')}
function split3D(){const raw=document.getElementById('splitter-input').value.trim(),items=raw.split(/[\s*#|,;]+/).map(x=>x.trim()).filter(Boolean),valid=items.filter(x=>/^\d{3}$/.test(x)),err=document.getElementById('splitter-error');if(!valid.length){err.textContent='Masukkan angka 3D terlebih dahulu.';err.style.display='block';document.getElementById('splitter-output').style.display='none';return}if(valid.length!==items.length){err.textContent=`${items.length-valid.length} item dilewati karena bukan format 3D.`;err.style.display='block'}else err.style.display='none';const cut=Math.ceil(valid.length/2);document.getElementById('splitter-a').value=valid.slice(0,cut).join('*');document.getElementById('splitter-b').value=valid.slice(cut).join('*');document.getElementById('splitter-output').style.display='block'}
function copySplitter(id,msg){const value=document.getElementById(id).value;if(value)copyText(value,msg)}
function sumReduce(n){n=Math.abs(Number(n)||0);while(n>=10)n=String(n).split('').reduce((a,c)=>a+Number(c),0);return n}
function parseHistoryResults(raw,last){let l=[];if(raw){try{const p=typeof raw==='string'?JSON.parse(raw):raw;if(Array.isArray(p))l=p.map(x=>String(x?.result??x))}catch{l=String(raw).match(/\b\d{4}\b/g)||[]}}if(!l.length&&last)l=[String(last)];return l.map(x=>String(x).padStart(4,'0')).filter(x=>/^\d{4}$/.test(x))}
function getCombinations5(){const combos=[];for(let a=0;a<6;a++)for(let b=a+1;b<7;b++)for(let c=b+1;c<8;c++)for(let d=c+1;d<9;d++)for(let e=d+1;e<10;e++)combos.push([a,b,c,d,e]);return combos}
const COMBOS=getCombinations5();
function baseR1(h,i){const d=h[i].split('').map(Number),[,kop,kep]=d;return ML[sumReduce(kop+kep+d[3])]}
function baseR2(h,i){const d=h[i].split('').map(Number),[as,kop,kep,ekor]=d;const next=h[i+1];if(!next)return null;const nd=next.split('').map(Number);return TY[sumReduce(ML[sumReduce(as+kop+kep+ekor)]+MB[sumReduce(kop+kep+ekor)]+((nd[2]+5)%10))]}
function baseR3(h,i){const d=h[i].split('').map(Number),kep=d[2];return(sumReduce(ML[d[0]]+MB[kep]+kep)+8)%10}
function baseR4(h,i){const d=h[i].split('').map(Number),kep=d[2],ekor=d[3];return((sumReduce(kep+ekor)-((kep+9)%10)+5)%10+10)%10}
function adaptiveFormula(history,baseFn){if(history.length<2)return null;const maxL=history.length-1;for(let L=1;L<=maxL;L++){const valid=[];for(const combo of COMBOS){let ok=true;for(let idx=1;idx<=L;idx++){const sourceIndex=idx,targetIndex=idx-1;if(sourceIndex>=history.length||targetIndex<0){ok=false;break}const base=baseFn(history,sourceIndex);if(base===null||base===undefined||Number.isNaN(base)){ok=false;break}const row=Array.from({length:10},(_,j)=>(base+j)%10),target2D=String(history[targetIndex]).slice(-2);if(!/^\d{2}$/.test(target2D)||!combo.some(col=>target2D.includes(String(row[col])))){ok=false;break}}if(ok)valid.push(combo)}if(valid.length){const latestBase=baseFn(history,0);if(latestBase===null||latestBase===undefined)return null;const latestRow=Array.from({length:10},(_,j)=>(latestBase+j)%10),digits=new Set();valid.forEach(combo=>combo.forEach(col=>digits.add(latestRow[col])));return{window:L,combos:valid,digits:[...digits]}}}return null}
function rankFour(results){const score=Array(10).fill(0);results.forEach(r=>{if(!r)return;const weight=1/(r.window||1);r.digits.forEach((d,pos)=>score[d]+=weight+0.02*(10-pos))});return score.map((s,d)=>({d,s})).sort((a,b)=>b.s-a.s||a.d-b.d).slice(0,4).map(x=>x.d).sort((a,b)=>a-b)}
function formatTen(main){const a=[...new Set(main)].sort((x,y)=>x-y),s=[];for(let d=0;d<10;d++)if(!a.includes(d))s.push(d);return{ai:a.join(''),nonAi:s.join(''),full:`${a.join('')} ${s.join('')}`}}
async function prosesPasaran(){const boxes=marketData.filter(m=>m.selected),em=document.getElementById('error-msg'),out=document.getElementById('output-container');if(!boxes.length){em.textContent='Silakan pilih minimal satu pasaran.';em.style.display='block';return}em.style.display='none';out.innerHTML='<div class="loading">Sedang menghitung...</div>';try{const data=await Promise.all(boxes.map(m=>api(`/api/markets/${encodeURIComponent(m.id)}`)));allAiResults=[];allNonAiResults=[];let html='';for(let i=0;i<boxes.length;i++){const m=data[i],name=String(m.name||boxes[i].name||m.id).toUpperCase(),history=parseHistoryResults(m.history_data,m.last_result);if(history.length<2){html+=`<div class="market-result-card"><div class="market-title">${name}</div><div style="color:#f87171;font-size:.78rem">Riwayat keluaran belum cukup (min 2 result).</div></div>`;continue}const results=[adaptiveFormula(history,baseR1),adaptiveFormula(history,baseR2),adaptiveFormula(history,baseR3),adaptiveFormula(history,baseR4)],main=rankFour(results);if(main.length<4){html+=`<div class="market-result-card"><div class="market-title">${name}</div><div style="color:#f87171;font-size:.78rem">Kandidat utama belum ditemukan.</div></div>`;continue}const final=formatTen(main);allAiResults.push(`[ ${name} ]\n${final.ai}`);allNonAiResults.push(`[ ${name} ]\n${final.nonAi}`);html+=`<div class="market-result-card"><div class="market-title">${name}</div><pre>${final.full}</pre></div>`}if(allAiResults.length)html+=`<div class="button-group"><button class="btn-copy" id="copy-ai">Salin Angka Utama</button><button class="btn-copy" id="copy-non-ai">Salin Angka Sisa</button></div>`;out.innerHTML=html;document.getElementById('copy-ai')?.addEventListener('click',()=>copyText(allAiResults.join('\n\n'),'Angka Utama Disalin!'));document.getElementById('copy-non-ai')?.addEventListener('click',()=>copyText(allNonAiResults.join('\n\n'),'Angka Sisa Disalin!'))}catch(err){console.error('prosesPasaran:',err);out.innerHTML=`<div style="text-align:center;color:#f87171;padding:15px;font-size:.78rem">Gagal mengambil data: ${err.message}</div>`}}
function copyText(t,msg){if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(t).then(()=>showToast(msg)).catch(()=>fallbackCopy(t,msg));else fallbackCopy(t,msg)}
function fallbackCopy(t,msg){const ta=document.createElement('textarea');ta.value=t;ta.style.position='fixed';ta.style.left='-9999px';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');showToast(msg)}catch{window.prompt('Salin manual:',t)}finally{ta.remove()}}
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2000)}
document.getElementById('process-button')?.addEventListener('click',prosesPasaran);document.getElementById('select-all')?.addEventListener('click',()=>toggleAll(true));document.getElementById('clear-all')?.addEventListener('click',()=>toggleAll(false));document.getElementById('market-search')?.addEventListener('input',renderMarkets);document.getElementById('open-tool')?.addEventListener('click',openTool);document.getElementById('close-tool')?.addEventListener('click',closeTool);document.getElementById('splitter-run')?.addEventListener('click',split3D);document.getElementById('copy-splitter-a')?.addEventListener('click',()=>copySplitter('splitter-a','Bagian 1 disalin!'));document.getElementById('copy-splitter-b')?.addEventListener('click',()=>copySplitter('splitter-b','Bagian 2 disalin!'));document.getElementById('splitter-modal')?.addEventListener('click',e=>{if(e.target.id==='splitter-modal')closeTool()});loadMarkets();