import { serveDir } from "https://deno.land/std@0.224.0/http/file_server.ts";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")?.replace(/\/$/,"")??"";
const SUPABASE_ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")??"";
const SESSION_SECRET=Deno.env.get("LOGIN_SESSION_SECRET")??"";
const MASTER_PIN=Deno.env.get("MASTER_PIN")??"";
const TTL=30*24*60*60*1000,MAXAGE=30*24*60*60,RL_WINDOW=60000,RL=60,LOGIN_RL=10,TIMEOUT=10000;
const requests=new Map<string,{count:number;reset:number}>(),loginRequests=new Map<string,{count:number;reset:number}>();
function headers(extra:Record<string,string>={}){return {"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","x-frame-options":"DENY","referrer-policy":"strict-origin-when-cross-origin","permissions-policy":"camera=(), microphone=(), geolocation=()","content-security-policy":"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'",...extra}}
function pageHeaders(extra:Record<string,string>={}){return headers({"content-type":"text/html; charset=utf-8",...extra})}
function ip(req:Request){return (req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown").slice(0,100)}
function limited(store:Map<string,{count:number;reset:number}>,key:string,limit:number){const now=Date.now(),x=store.get(key);if(!x||now>=x.reset){store.set(key,{count:1,reset:now+RL_WINDOW});return false}x.count++;return x.count>limit}
function rate(req:Request){return limited(requests,ip(req),RL)}
function loginRate(req:Request){return limited(loginRequests,ip(req),LOGIN_RL)}
function json(data:unknown,status=200,extra:Record<string,string>={}){return new Response(JSON.stringify(data),{status,headers:headers(extra)})}
function b64(data:Uint8Array|string){const bytes=typeof data==='string'?new TextEncoder().encode(data):data;let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(v:string){v=v.replace(/-/g,'+').replace(/_/g,'/');while(v.length%4)v+='=';return Uint8Array.from(atob(v),c=>c.charCodeAt(0))}
async function sign(v:string){if(!SESSION_SECRET)throw new Error('LOGIN_SESSION_SECRET belum dikonfigurasi.');const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(v))))}
async function session(user:string){const p=b64(JSON.stringify({u:user,e:Date.now()+TTL}));return `${p}.${await sign(p)}`}
async function getSession(req:Request){const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)lia_session=([^;]+)/)?.[1];if(!raw||!SESSION_SECRET)return null;const [p,s]=raw.split('.');if(!p||!s)return null;try{const e=await sign(p);if(s.length!==e.length)return null;let d=0;for(let i=0;i<s.length;i++)d|=s.charCodeAt(i)^e.charCodeAt(i);if(d!==0)return null;const x=JSON.parse(new TextDecoder().decode(unb64(p)));return x?.u&&Date.now()<=Number(x.e)?String(x.u):null}catch{return null}}
function cookie(t:string){return `lia_session=${t}; Path=/; Max-Age=${MAXAGE}; HttpOnly; Secure; SameSite=Strict`}
function clearCookie(){return 'lia_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict'}
async function supabaseGet(path:string){if(!SUPABASE_URL||!SUPABASE_ANON_KEY)throw new Error('Backend Supabase configuration is missing.');const c=new AbortController(),timer=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,Accept:'application/json'},signal:c.signal});const body=await r.text();if(!r.ok)throw new Error(`Supabase request failed (${r.status}).`);return body?JSON.parse(body):[]}finally{clearTimeout(timer)}}
async function servePage(req:Request,path:string){return serveDir(new Request(new URL(path,req.url),req),{fsRoot:'.',showIndex:true})}
Deno.serve(async req=>{const url=new URL(req.url);
if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers({'access-control-allow-origin':'*','access-control-allow-methods':'GET, POST, OPTIONS','access-control-allow-headers':'Content-Type'})});
if(url.pathname==='/api/login'&&req.method==='POST'){if(loginRate(req))return json({ok:false,error:'Terlalu banyak percobaan login. Coba lagi nanti.'},429,{'retry-after':'60'});try{const b=await req.json(),user=String(b?.user??'').trim().toLowerCase(),password=String(b?.password??'');if(!['user1','user2','user3'].includes(user)||!password||password.length>256)return json({ok:false,error:'Login tidak valid.'},401);const expected=String(Deno.env.get(`LOGIN_PASS${user.slice(-1)}`)??'');if(password!==MASTER_PIN&&password!==expected)return json({ok:false,error:'Password salah.'},401);const token=await session(user);return json({ok:true,user,redirect:`/${user}/`},200,{'set-cookie':cookie(token)})}catch(e){console.error('POST /api/login',e);return json({ok:false,error:'Permintaan login tidak valid.'},400)}}
if(url.pathname==='/api/logout'&&req.method==='POST')return json({ok:true},200,{'set-cookie':clearCookie()});
if(url.pathname==='/api/session'&&req.method==='GET'){const user=await getSession(req);return json({ok:Boolean(user),user})}
if(rate(req))return json({error:'Too many requests. Try again later.'},429,{'retry-after':'60'});
if(url.pathname==='/api/health'&&req.method==='GET')return json({ok:true,supabase_configured:Boolean(SUPABASE_URL&&SUPABASE_ANON_KEY),auth_configured:Boolean(SESSION_SECRET&&Deno.env.get('LOGIN_PASS1')&&Deno.env.get('LOGIN_PASS2')&&Deno.env.get('LOGIN_PASS3')),master_pin_configured:Boolean(MASTER_PIN)});
if(url.pathname==='/api/markets'&&req.method==='GET'){if(!(await getSession(req)))return json({error:'Unauthorized.'},401);try{return json(await supabaseGet('markets?select=id,name,order,last_result&order=order.asc'))}catch(e){console.error(e);return json({error:'Failed to load markets.'},502)}}
if(url.pathname.startsWith('/api/markets/')&&req.method==='GET'){if(!(await getSession(req)))return json({error:'Unauthorized.'},401);const id=decodeURIComponent(url.pathname.slice('/api/markets/'.length));if(!id||id.length>120||/[\r\n]/.test(id))return json({error:'Invalid market id.'},400);try{const rows=await supabaseGet(`markets?select=id,name,history_data,last_result&id=eq.${encodeURIComponent(id)}&limit=1`);if(!Array.isArray(rows)||!rows.length)return json({error:'Market not found.'},404);return json(rows[0])}catch(e){console.error(e);return json({error:'Failed to load market.'},502)}}
if(url.pathname==='/config.js')return new Response('window.SUPABASE_URL=undefined;window.SUPABASE_ANON_KEY=undefined;',{headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const user=await getSession(req);
if(url.pathname==='/login.html'||url.pathname==='/login.js')return serveDir(req,{fsRoot:'.',showIndex:true});
if(url.pathname==='/'||url.pathname==='/index.html'){if(!user)return new Response(null,{status:302,headers:{location:'/login.html',...pageHeaders()}});return new Response(null,{status:302,headers:{location:`/${user}/`,...pageHeaders()}})}
for(const u of ['user1','user2','user3']){if(url.pathname===`/${u}`||url.pathname===`/${u}/`){if(user!==u)return new Response(null,{status:302,headers:{location:user?`/${user}/`:'/login.html',...pageHeaders()}});const path=u==='user1'?'/index.html':`/${u}/index.html`;const r=await servePage(req,path);return new Response(r.body,{status:r.status,headers:r.headers})}}
const r=await serveDir(req,{fsRoot:'.',showIndex:true});const h=new Headers(r.headers);for(const [k,v] of Object.entries(headers()))if(k!=='content-type'&&k!=='cache-control')h.set(k,v);return new Response(r.body,{status:r.status,headers:h})});