import { serveDir } from "https://deno.land/std@0.224.0/http/file_server.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")?.replace(/\/$/, "") ?? "";
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
const SESSION_SECRET = Deno.env.get("LOGIN_SESSION_SECRET") ?? "";
const SESSION_TTL_MS = 30 * 24 * 60 * 60 * 1000;
const SESSION_MAX_AGE = 30 * 24 * 60 * 60;
const RATE_WINDOW_MS = 60_000;
const RATE_LIMIT = 60;
const LOGIN_RATE_LIMIT = 10;
const SUPABASE_TIMEOUT_MS = 10_000;
const requests = new Map<string, { count: number; reset: number }>();
const loginRequests = new Map<string, { count: number; reset: number }>();

function securityHeaders(extra: Record<string, string> = {}) { return { "content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","x-frame-options":"DENY","referrer-policy":"strict-origin-when-cross-origin","permissions-policy":"camera=(), microphone=(), geolocation=()","content-security-policy":"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none',...extra }; }
function pageHeaders(extra: Record<string,string>={}) { const h=securityHeaders({"content-type":"text/html; charset=utf-8",...extra}); delete h["cache-control"]; h["cache-control"]="no-store"; return h; }
function clientIp(req: Request) { return (req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown").slice(0,100); }
function limited(store: Map<string,{count:number;reset:number}>,key:string,limit:number) { const now=Date.now(),current=store.get(key); if(!current||now>=current.reset){store.set(key,{count:1,reset:now+RATE_WINDOW_MS});return false;} current.count++; return current.count>limit; }
function rateLimited(req: Request) { return limited(requests,clientIp(req),RATE_LIMIT); }
function loginRateLimited(req: Request) { return limited(loginRequests,clientIp(req),LOGIN_RATE_LIMIT); }
async function supabaseGet(path:string){ if(!SUPABASE_URL||!SUPABASE_ANON_KEY)throw new Error("Backend Supabase configuration is missing."); const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),SUPABASE_TIMEOUT_MS); try{const response=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,Accept:"application/json"},signal:controller.signal});const body=await response.text();if(!response.ok){console.error("Supabase HTTP",response.status,body.slice(0,500));throw new Error(`Supabase request failed (${response.status}).`);}return body?JSON.parse(body):[];}finally{clearTimeout(timer);}}
function json(data:unknown,status=200,extra:Record<string,string>={}){return new Response(JSON.stringify(data),{status,headers:securityHeaders(extra)});}
function b64(data:Uint8Array|string){const bytes=typeof data==='string'?new TextEncoder().encode(data):data;let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function unb64(s:string){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0));}
async function sign(value:string){if(!SESSION_SECRET)throw new Error('LOGIN_SESSION_SECRET belum dikonfigurasi.');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value))));}
async function makeSession(user:string){const payload=b64(JSON.stringify({u:user,e:Date.now()+SESSION_TTL_MS}));return `${payload}.${await sign(payload)}`;}
async function getSession(req:Request){const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)lia_session=([^;]+)/)?.[1];if(!raw||!SESSION_SECRET)return null;const [payload,sig]=raw.split('.');if(!payload||!sig)return null;try{const expected=await sign(payload);if(sig.length!==expected.length)return null;let diff=0;for(let i=0;i<sig.length;i++)diff|=sig.charCodeAt(i)^expected.charCodeAt(i);if(diff!==0)return null;const data=JSON.parse(new TextDecoder().decode(unb64(payload)));if(!data?.u||Date.now()>Number(data.e))return null;return String(data.u);}catch{return null;}}
function sessionCookie(token:string){return `lia_session=${token}; Path=/; Max-Age=${SESSION_MAX_AGE}; HttpOnly; Secure; SameSite=Strict`}
function clearCookie(){return `lia_session=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict`}
async function servePage(req:Request,path:string){return serveDir(new Request(new URL(path,req.url),req),{fsRoot:".",showIndex:true});}

Deno.serve(async(req)=>{const url=new URL(req.url);
if(req.method==="OPTIONS")return new Response(null,{status:204,headers:securityHeaders({"access-control-allow-origin":"*","access-control-allow-methods":"GET, POST, OPTIONS","access-control-allow-headers":"Content-Type"})});
if(url.pathname==="/api/login"&&req.method==="POST"){if(loginRateLimited(req))return json({ok:false,error:"Terlalu banyak percobaan login. Coba lagi nanti."},429,{"retry-after":"60"});try{const body=await req.json();const user=String(body?.user??'').trim().toLowerCase();const password=String(body?.password??'');if(!['user1','user2'].includes(user)||password.length===0||password.length>256)return json({ok:false,error:'Login tidak valid.'},401);const expected=String(user==='user1'?Deno.env.get('LOGIN_PASS1')??'':Deno.env.get('LOGIN_PASS2')??'');if(expected.length===0||password!==expected)return json({ok:false,error:'Password salah.'},401);const token=await makeSession(user);return json({ok:true,user,redirect:user==='user1'?'/user1/':'/user2/'},200,{"set-cookie":sessionCookie(token)});}catch(error){console.error('POST /api/login',error);return json({ok:false,error:'Permintaan login tidak valid.'},400);}}
if(url.pathname==="/api/logout"&&req.method==="POST")return json({ok:true},200,{"set-cookie":clearCookie()});
if(url.pathname==="/api/session"&&req.method==="GET"){const user=await getSession(req);return json({ok:Boolean(user),user});}
if(rateLimited(req))return json({error:"Too many requests. Try again later."},429,{"retry-after":"60"});
if(url.pathname==="/api/health"&&req.method==="GET")return json({ok:true,supabase_configured:Boolean(SUPABASE_URL&&SUPABASE_ANON_KEY),auth_configured:Boolean(SESSION_SECRET&&Deno.env.get('LOGIN_PASS1')&&Deno.env.get('LOGIN_PASS2'))});
if(url.pathname==="/api/markets"&&req.method==="GET"){if(!(await getSession(req)))return json({error:'Unauthorized.'},401);try{return json(await supabaseGet("markets?select=id,name,order,last_result&order=order.asc"));}catch(error){console.error("GET /api/markets",error);const message=error instanceof DOMException&&error.name==="AbortError"?"Supabase request timed out.":error instanceof Error&&error.message==="Backend Supabase configuration is missing."?error.message:"Failed to load markets.";return json({error:message},502);}}
if(url.pathname.startsWith("/api/markets/")&&req.method==="GET"){if(!(await getSession(req)))return json({error:'Unauthorized.'},401);const id=decodeURIComponent(url.pathname.slice("/api/markets/".length));if(!id||id.length>120||/[\r\n]/.test(id))return json({error:"Invalid market id."},400);try{const markets=await supabaseGet(`markets?select=id,name,history_data,last_result&id=eq.${encodeURIComponent(id)}&limit=1`);if(!Array.isArray(markets)||!markets.length)return json({error:"Market not found."},404);return json(markets[0]);}catch(error){console.error(`GET /api/markets/${id}`,error);const message=error instanceof DOMException&&error.name==="AbortError"?"Supabase request timed out.":error instanceof Error&&error.message==="Backend Supabase configuration is missing."?error.message:"Failed to load market.";return json({error:message},502);}}
if(url.pathname==="/config.js")return new Response("window.SUPABASE_URL=undefined;window.SUPABASE_ANON_KEY=undefined;",{status:200,headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
const user=await getSession(req);
if(url.pathname==="/login.html"||url.pathname==="/login.js")return serveDir(req,{fsRoot:".",showIndex:true});
if(url.pathname==="/"||url.pathname==="/index.html"){if(!user)return new Response(null,{status:302,headers:{location:'/login.html',...pageHeaders()}});if(user!=='user1')return new Response(null,{status:302,headers:{location:'/user2/',...pageHeaders()}});return serveDir(req,{fsRoot:".",showIndex:true});}
if(url.pathname==="/user1"||url.pathname==="/user1/"){if(user!=='user1')return new Response(null,{status:302,headers:{location:user==="user2"?'/user2/':'/login.html',...pageHeaders()}});const response=await servePage(req,'/index.html');return new Response(response.body,{status:response.status,headers:response.headers});}
if(url.pathname==="/user2"||url.pathname==="/user2/"){if(user!=='user2')return new Response(null,{status:302,headers:{location:user==="user1"?'/user1/':'/login.html',...pageHeaders()}});const response=await servePage(req,'/user2/index.html');return new Response(response.body,{status:response.status,headers:response.headers});}
const response=await serveDir(req,{fsRoot:".",showIndex:true}),headers=new Headers(response.headers);headers.set("x-content-type-options","nosniff");headers.set("x-frame-options","DENY");headers.set("referrer-policy","strict-origin-when-cross-origin");headers.set("permissions-policy","camera=(), microphone=(), geolocation=()");headers.set("content-security-policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; frame-ancestors 'none'");return new Response(response.body,{status:response.status,headers});});