const ML={0:1,1:0,2:5,3:8,4:7,5:2,6:9,7:4,8:3,9:6};
const MB={0:8,1:7,2:6,3:9,4:5,5:4,6:2,7:1,8:0,9:3};
const TY={0:7,7:0,1:4,4:1,2:9,9:2,3:6,6:3,5:8,8:5};
const IND=n=>(n+5)%10;
let marketData=[],allResults=[];
function setLoading(m,e=false){const x=document.getElementById('loading-markets');if(x){x.textContent=m;x.style.color=e?'#ef4444':'var(--muted)'}}
async function api(p){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(p,{headers:{Accept:'application/json'},cache:'no-store',signal:c.signal});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`Request gagal (${r.status})`);return b}catch(e){if(e.name==='AbortError')throw new Error('Server tidak merespons.');throw e}finally{clearTimeout(t)}}
async function logout(){const b=document.getElementById('logout-button');if(b){b.disabled=true;b.textContent='LOG OUT...'}try{await fetch('/api/logout',{method:'POST',credentials:'include',cache:'no-store'})}finally{location.replace('/login.html')}}
function updateCount(){document.getElementById('market-count').textContent=`${marketData.filter(m=>m.selected).length} dipilih`}
function renderMarkets(){const l=document.getElementById('market-list'),q=(document.getElementById('market-search').value||'').trim().toUpperCase();l.innerHTML='';marketData.filter(m=>String(m.name||m.id).toUpperCase().includes(q)).forEach(m=>{const z=document.createElement('label');z.className='market-chip';const i=document.createElement('input');i.type='checkbox';i.checked=!!m.selected;i.addEventListener('change',()=>{m.selected=i.checked;z.classList.toggle('active',i.checked);updateCount()});const a=document.createElement('span');a.className='market-name';a.textContent=String(m.name||m.id).toUpperCase();const b=document.createElement('span');b.className='market-last';b.textContent=m.last_result==null?'':String(m.last_result).padStart(4,'0');z.append(i,a,b);if(m.selected)z.classList.add('active');l.append(z)})}
async function loadMarkets(){setLoading('Memuat data pasaran...');try{const d=await api('/api/markets');if(!Array.isArray(d)||!d.length)return setLoading('Data pasaran tidak tersedia.',true);marketData=d.map(m=>({...m,selected:false}));document.getElementById('loading-markets').style.display='none';document.getElementById('market-list').style.display='grid';renderMarkets();updateCount()}catch(e){setLoading(`Gagal memuat pasaran: ${e.message}`,true)}}
function history(raw,last){let a=[];try{const p=typeof raw==='string'?JSON.parse(raw):raw;if(Array.isArray(p))a=p.map(x=>String(x?.result??x))}catch{a=String(raw||'').match(/\b\d{4}\b/g)||[]}if(!a.length&&last!=null)a=[String(last)];return a.map(x=>x.padStart(4,'0')).filter(x=>/^\d{4}$/.test(x))}
function uniq7(arr,seed=[]){const out=[];for(const n of arr.map(Number))if(Number.isInteger(n)&&n>=0&&n<=9&&!out.includes(n))out.push(n);if(out.length<7){for(const n of seed.map(Number))if(!out.includes(n)){out.push(n);if(out.length===7)break}}if(out.length<7){for(let n=0;n<10&&out.length<7;n++)if(!out.includes(n))out.push(n)}return out.slice(0,7)}
function forward(x){return Array.from({length:7},(_,i)=>(x+i)%10)}
function f1(d){return forward((d[0]+d[1])%10)}
function f2(d){return forward((d[0]+d[3])%10)}
function f3(d){return forward((d[1]+d[2])%10)}
function f4(d){const c=d[2];return uniq7([c,ML[c],MB[c],IND(c),c+1,c+2,c-1])}
function f5(d){const x=d[3];return uniq7([x,TY[x],IND(x),ML[x],MB[x],x+1,x-1])}
function f6(d){const a=d[0];return uniq7([a,ML[a],MB[a],IND(a),a+1,a+2,a+3])}
function f7(d){const b=d[1];return uniq7([b,ML[b],MB[b],IND(b),b+1,b+2,b-1])}
function f8(d){const [a,b,c,e]=d,E=(a+b)%10,F=(b+c)%10,G=(c+e)%10,H=(E+F)%10,I=(F+G)%10,J=(H+I)%10;return uniq7([a,b,c,e,E,F,G,H,I,J],[IND(J)])}
function f9(d){const s1=Math.abs(d[0]-d[1]),s2=Math.abs(d[2]-d[3]);return uniq7([s1,s2,IND(s1),IND(s2),ML[s1],MB[s2],(s1+s2)%10])}
function f10(d){const x1=Math.abs(d[0]-d[3]),x2=Math.abs(d[1]-d[2]);return uniq7([x1,x2,IND(x1),IND(x2),TY[x1],TY[x2],(x1+x2)%10])}
function f11(d){const x=Math.abs(parseInt(d.slice(0,2).join(''),10)-parseInt(d.slice(2).join(''),10));const a=Math.floor(x/10)%10,b=x%10;return uniq7([a,b,IND(a),IND(b),ML[a],MB[b],(a+1)%10])}
function f12(d){const c=d[2],e=d[3];const t1=TY[c]*10+TY[e],t2=(c*10+e+50)%100;return uniq7([c,e,Math.floor(t1/10),t1%10,Math.floor(t2/10),t2%10,IND(e)])}
function f13(d){const a=d[0],b=d[1];const t1=TY[a]*10+TY[b];return uniq7([a,b,Math.floor(t1/10),t1%10,IND(a),IND(b),ML[b]])}
function digitalRoot(n){n=Math.abs(Number(n));while(n>=10)n=String(n).split('').reduce((s,x)=>s+Number(x),0);return n}
function f14(d){const b=digitalRoot(d.reduce((s,x)=>s+x,0));return uniq7([b,IND(b),ML[b],MB[b],b+1,b+2,b-1])}
function f15(hist){if(hist.length<8)return null;const a=Number(hist[0][0]),a2=Number(hist[7][0]),x=(a+a2)%10;return uniq7([x,x+1,x+2,x+3,IND(x),ML[x],MB[x]])}
function f16(hist){if(hist.length<8)return null;const b=Number(hist[0][1]),b2=Number(hist[7][1]),y=(b+b2)%10;return uniq7([y,y+1,y+2,y+3,y+4,IND(y),IND(y+1)])}
function f17(hist){const vals=[...new Set(hist.slice(0,2).flat().map(Number))];if(vals.length>7){const oldAs=Number(hist[1][0]);const i=vals.indexOf(oldAs);if(i>=0)vals.splice(i,1)}if(vals.length<7){const freq={};hist.slice(0,2).flat().forEach(n=>freq[n]=(freq[n]||0)+1);const ranked=Object.keys(freq).map(Number).sort((a,b)=>freq[b]-freq[a]||a-b);for(const n of ranked)if(!vals.includes(n)){vals.push(n);if(vals.length===7)break}}return uniq7(vals)}
function f18(d){const banned=new Set([d[3],IND(d[0]),ML[d[3]]]);return Array.from({length:10},(_,n)=>n).filter(n=>!banned.has(n)).slice(0,7)}
function run18(hist){const d=hist[0].split('').map(Number);const fs=[f1(d),f2(d),f3(d),f4(d),f5(d),f6(d),f7(d),f8(d),f9(d),f10(d),f11(d),f12(d),f13(d),f14(d),f15(hist),f16(hist),f17(hist),f18(d)].filter(Boolean).map(uniq7);const vote=Array(10).fill(0);fs.forEach(r=>new Set(r).forEach(n=>vote[n]++));const final=Array.from({length:10},(_,n)=>n).sort((a,b)=>vote[b]-vote[a]||a-b).slice(0,7).sort((a,b)=>a-b);return {digits:final,votes:vote,formulaCount:fs.length}}
async function prosesPasaran(){const boxes=marketData.filter(m=>m.selected),em=document.getElementById('error-msg'),out=document.getElementById('output-container'),btn=document.getElementById('process-button');if(!boxes.length){em.textContent='Silakan pilih minimal satu pasaran.';em.style.display='block';return}em.style.display='none';btn.disabled=true;btn.textContent='MENGHITUNG...';btn.style.opacity='.7';out.innerHTML='<div class="loading" style="padding:30px 10px;text-align:center"><span style="display:inline-block;width:18px;height:18px;border:2px solid var(--line);border-top-color:var(--accent);border-radius:50%;animation:spin .7s linear infinite;vertical-align:middle;margin-right:8px"></span>Menghitung hasil...</div>';requestAnimationFrame(()=>out.scrollIntoView({behavior:'smooth',block:'start'}));try{const data=await Promise.all(boxes.map(m=>api(`/api/markets/${encodeURIComponent(m.id)}`)));allResults=[];let html='';for(let i=0;i<boxes.length;i++){const m=data[i],name=String(m.name||boxes[i].name||m.id).toUpperCase(),h=history(m.history_data,m.last_result);if(!h.length){html+=`<div class="market-result-card"><div class="market-title">${esc(name)}</div><div style="color:#f87171;font-size:.78rem">Result belum tersedia.</div></div>`;continue}const r=run18(h);const value=r.digits.join('');allResults.push(`[ ${name} ]\n${value}`);html+=`<div class="market-result-card"><div class="market-title">${esc(name)}</div><pre>${value}</pre></div>`}if(allResults.length)html+='<div class="button-group"><button class="btn-copy" id="copy-ai">Salin Hasil BBFS 7 Digit</button></div>';out.innerHTML=html;document.getElementById('copy-ai')?.addEventListener('click',()=>copyText(allResults.join('\n\n'),'Hasil BBFS 7 Digit Disalin!'));requestAnimationFrame(()=>out.scrollIntoView({behavior:'smooth',block:'start'}))}catch(e){out.innerHTML=`<div style="text-align:center;color:#f87171;padding:15px;font-size:.78rem">Gagal mengambil data: ${esc(e.message)}</div>`;out.scrollIntoView({behavior:'smooth',block:'start'})}finally{btn.disabled=false;btn.textContent='PROSES HASIL';btn.style.opacity='1'}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function copyText(t,m){if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(t).then(()=>toast(m)).catch(()=>fallback(t,m));else fallback(t,m)}function fallback(t,m){const a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.left='-9999px';document.body.append(a);a.select();try{document.execCommand('copy');toast(m)}finally{a.remove()}}function toast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2000)}
document.getElementById('process-button')?.addEventListener('click',prosesPasaran);document.getElementById('select-all')?.addEventListener('click',()=>{marketData.forEach(m=>m.selected=true);renderMarkets();updateCount()});document.getElementById('clear-all')?.addEventListener('click',()=>{marketData.forEach(m=>m.selected=false);renderMarkets();updateCount()});document.getElementById('market-search')?.addEventListener('input',renderMarkets);document.getElementById('logout-button')?.addEventListener('click',logout);const s=document.createElement('style');s.textContent='@keyframes spin{to{transform:rotate(360deg)}}';document.head.appendChild(s);loadMarkets();