const ML={0:1,1:0,2:5,3:8,4:7,5:2,6:9,7:4,8:3,9:6},MB={0:8,1:7,2:6,3:9,4:5,5:4,6:2,7:1,8:0,9:3};let marketData=[];
function setLoading(m,e=false){const x=document.getElementById('loading-markets');if(x){x.textContent=m;x.style.color=e?'#ef4444':'var(--muted)'}}
async function api(p){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(p,{headers:{Accept:'application/json'},cache:'no-store',signal:c.signal});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.error||`Request gagal (${r.status})`);return b}catch(e){if(e.name==='AbortError')throw new Error('Server tidak merespons.');throw e}finally{clearTimeout(t)}}
function updateCount(){document.getElementById('market-count').textContent=`${marketData.filter(m=>m.selected).length} dipilih`}
function renderMarkets(){const l=document.getElementById('market-list'),q=(document.getElementById('market-search').value||'').trim().toUpperCase();l.innerHTML='';const f=marketData.filter(m=>String(m.name||m.id).toUpperCase().includes(q));if(!f.length){l.innerHTML='<div class="empty">Pasaran tidak ditemukan.</div>';return}f.forEach(m=>{const n=String(m.name||m.id).toUpperCase(),r=m.last_result==null?'':String(m.last_result).padStart(4,'0'),z=document.createElement('label');z.className='market-chip';const i=document.createElement('input');i.type='checkbox';i.value=m.id;i.checked=!!m.selected;i.addEventListener('change',()=>{m.selected=i.checked;z.classList.toggle('active',i.checked);updateCount()});const a=document.createElement('span');a.className='market-name';a.textContent=n;const b=document.createElement('span');b.className='market-last';b.textContent=r||'—';z.append(i,a,b);if(m.selected)z.classList.add('active');l.append(z)})}
async function loadMarkets(){setLoading('Memuat data pasaran...');try{const d=await api('/api/markets');if(!Array.isArray(d)||!d.length){setLoading('Data pasaran tidak tersedia.',true);return}marketData=d.map(m=>({...m,selected:false}));document.getElementById('loading-markets').style.display='none';document.getElementById('market-list').style.display='grid';renderMarkets();updateCount()}catch(e){console.error('loadMarkets:',e);setLoading(`Gagal memuat pasaran: ${e.message}`,true)}}
function toggleAll(v){marketData.forEach(m=>m.selected=v);renderMarkets();updateCount()}
function parseHistoryResults(raw,last){let l=[];if(raw){try{const p=typeof raw==='string'?JSON.parse(raw):raw;if(Array.isArray(p))l=p.map(x=>String(x?.result??x))}catch{l=String(raw).match(/\b\d{4}\b/g)||[]}}if(!l.length&&last)l=[String(last)];return l.map(x=>x.padStart(4,'0')).filter(x=>/^\d{4}$/.test(x))}
function getBaseX1(result4D){const d=String(result4D).padStart(4,'0').split('').map(Number),[as,kop,kep]=d;const j1ml=ML[as%10],j3d1mb=MB[(((as+kop+kep)%10)+1)%10],c2m5=(kop-5+10)%10;return(j1ml+j3d1mb+c2m5)%10}
function getBaseX2(result4D){const d=String(result4D).padStart(4,'0').split('').map(Number),[as,kop,kep]=d;const a3mo=ML[(as+3)%10],c3mb=MB[(kop+3)%10],k3m0=(kep+3)%10;return(a3mo+c3mb+k3m0)%10}
function getCombinations5(){const combos=[];for(let a=0;a<6;a++)for(let b=a+1;b<7;b++)for(let c=b+1;c<8;c++)for(let d=c+1;d<9;d++)for(let e=d+1;e<10;e++)combos.push([a,b,c,d,e]);return combos}
const COMBOS=getCombinations5();
function processIncremental(history,getBaseX){const maxL=history.length-1;for(let L=1;L<=maxL;L++){const slice=history.slice(0,L+1);const valid=COMBOS.find(combo=>slice.every((item,idx)=>{if(idx===slice.length-1)return true;const target2D=String(slice[idx-1]).slice(-2),baseX=getBaseX(item),row=Array.from({length:10},(_,i)=>(baseX+i)%10);return combo.some(colIdx=>target2D.includes(String(row[colIdx])))}));if(valid){const latestBase=getBaseX(history[0]),row=Array.from({length:10},(_,i)=>(latestBase+i)%10),ai=[...new Set(valid.map(i=>row[i]).sort((a,b)=>a-b))],columns=valid.map(i=>String.fromCharCode(65+i)).join('');return{window:L,columns,ai}}}return null}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function prosesPasaran(){const boxes=marketData.filter(m=>m.selected),em=document.getElementById('error-msg'),out=document.getElementById('output-container');if(!boxes.length){em.textContent='Silakan pilih minimal satu pasaran.';em.style.display='block';return}em.style.display='none';out.innerHTML='<div class="loading">Sedang menghitung...</div>';try{const data=await Promise.all(boxes.map(m=>api(`/api/markets/${encodeURIComponent(m.id)}`)));let html='';for(let i=0;i<boxes.length;i++){const m=data[i],name=String(m.name||boxes[i].name||m.id).toUpperCase(),history=parseHistoryResults(m.history_data,m.last_result);if(history.length<2){html+=`<div class="market-result-card"><div class="market-title">${escapeHtml(name)}</div><div style="color:#f87171;font-size:.78rem">Riwayat keluaran belum cukup (minimal 2 result).</div></div>`;continue}const r1=processIncremental(history,getBaseX1),r2=processIncremental(history,getBaseX2);html+=`<div class="market-result-card"><div class="market-title">${escapeHtml(name)}</div><div style="font-size:.68rem;color:var(--muted);font-weight:700;margin-bottom:3px">AI 5 DIGIT • RUMUS 1</div>${r1?`<pre>${r1.ai.join(' . ')}</pre><div style="font-size:.68rem;color:var(--muted)">WINDOW ${r1.window} • KOLOM ${r1.columns}</div>`:'<div style="color:#f87171;font-size:.75rem">Tidak ditemukan Patah 0.</div>'}<div style="height:10px"></div><div style="font-size:.68rem;color:var(--muted);font-weight:700;margin-bottom:3px">AI 5 DIGIT • RUMUS 2</div>${r2?`<pre>${r2.ai.join(' . ')}</pre><div style="font-size:.68rem;color:var(--muted)">WINDOW ${r2.window} • KOLOM ${r2.columns}</div>`:'<div style="color:#f87171;font-size:.75rem">Tidak ditemukan Patah 0.</div>'}</div>`}out.innerHTML=html}catch(e){console.error('prosesPasaran:',e);out.innerHTML=`<div style="text-align:center;color:#f87171;padding:15px;font-size:.78rem">Gagal mengambil data: ${escapeHtml(e.message)}</div>`}}
function copyText(t,m){if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(t).then(()=>showToast(m)).catch(()=>fallbackCopy(t,m));else fallbackCopy(t,m)}function fallbackCopy(t,m){const a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.left='-9999px';document.body.appendChild(a);a.select();try{document.execCommand('copy');showToast(m)}catch{window.prompt('Salin manual:',t)}finally{a.remove()}}function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',2000)}
document.getElementById('process-button')?.addEventListener('click',prosesPasaran);document.getElementById('select-all')?.addEventListener('click',()=>toggleAll(true));document.getElementById('clear-all')?.addEventListener('click',()=>toggleAll(false));document.getElementById('market-search')?.addEventListener('input',renderMarkets);loadMarkets();